version: 2

jobs:
  check-links:
    docker:
      - image: web3f/link-checker:v0.1.0
    steps:
      - checkout
      - run:
          name: build
          command: |
            cd website
            yarn

      - run:
          name: serve
          background: true
          command: |
            cd website
            yarn start

      - run:
          name: wait website up
          command: |
            while ! nc -z localhost 3000; do
              sleep 1
              echo waiting for website up...
            done

      - run:
          name: check links
          command: |
            pylinkvalidate.py --parser=html5lib -P http://localhost:3000/docs/en -d 0

  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.2

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "polkadot-wiki-deploy@users.noreply.github.com"
            git config --global user.name "Polkadot Wiki CI"
            echo "machine github.com login w3fbot password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=w3fbot yarn run publish-gh-pages


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - check-links:
          filters:
            tags:
              only: /.*/
      - deploy-website:
          filters:
            branches:
              only: master
