version: 2

jobs:
  check-format:
    docker:
      - image: circleci/node:10.15.2   
    steps:
      - checkout
      - run:
          name: prettier
          command: |
            npm i prettier
            node_modules/.bin/prettier -c docs/*.md

  check-links:
    docker:
      - image: web3f/link-checker:v1.0.1
    steps:
      - checkout
      - run:
          name: build
          command: |
            yarn

      - run:
          name: serve
          background: true
          command: |
            yarn polkadot:start

      - run:
          name: wait website up
          command: |
            while ! nc -z localhost 3000; do
              sleep 1
              echo waiting for website up...
            done

      - run:
          name: check links
          command: |
            linkchecker --ignore-url="^(?:(?!\/en\/).)*$" --check-extern http://localhost:3000/

  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.2

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "polkadot-wiki-deploy@users.noreply.github.com"
            git config --global user.name "Polkadot Wiki CI"
            echo "machine github.com login w3fbot password $GITHUB_TOKEN" > ~/.netrc
            yarn && GIT_USER=w3fbot PUBLISHING=true yarn run publish-gh-pages

  deploy-kusama:
    docker:
      - image: circleci/node:10.15.2
    
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "polkadot-wiki-deploy@users.noreply.github.com"
            git config --global user.name "Polkadot Wiki CI"
            echo "machine github.com login w3fbot password $GITHUB_TOKEN" > ~/.netrc
            yarn && GIT_USER=w3fbot PUBLISHING=true PROJECT_NAME=kusama-guide-hosting CI_PULL_REQUEST=false yarn run kusama:publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - check-format:
          filters:
            tags:
              only: /.*/
      - check-links:
          filters:
            tags:
              only: /.*/
      - deploy-website:
          filters:
            branches:
              only: master
      - deploy-kusama:
          filters:
            branches:
              only: deployment-fix
