name: Generate downloadable PDF

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-pdf:
    name: Run the site and generate a PDF from it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Clone and run the site
        run: |
          yarn
          yarn polkadot:start &
          while ! nc -z localhost 3000; do
              sleep 1
              echo waiting for website up...
          done
          yarn polkadot:pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: polkadot-wiki
          path: website/static/polkadot-wiki.pdf
