name: Stale Check # stale pages (those that have not been updated in more than 21 days)

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  # check for stale pages
  check-stale:
    name: Checks for stale files
    runs-on: ubuntu-latest
    env: 
      REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find Docs
        id:   find
        uses: w3f/action-find-old-files@master
      - uses: actions/upload-artifact@v2
        with:
          name: Stale docs
          path: ${{ steps.find.outputs.files }}
      - name: Create Issues
        uses: w3f/action-create-issues-for-old-files@master
        with:
          randAssignees: '["jakehemmerle", "dannys03", "emresurmeli", "DrW3RK"]'
          files: ${{ steps.find.outputs.files }}
